name: soccer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.6
environment:
  sdk: ">=3.1.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.5
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9
  timelines: ^0.1.0
  accordion: ^2.6.0
  animations: ^2.0.8
  http: ^1.1.0
  image_picker: ^1.0.4
  dio: ^5.3.3
  intl: ^0.18.1
  data_table_2: ^2.5.9
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/bottom_navs/
    - assets/leagues/
    - assets/
  #   - images/a_dot_ham.jpeg

# setting up UI launcher splash screen
flutter_native_splash:
  color: "##FAFAFA"
  image: assets/images/png_logo.png
  android_12:
    color: "##FAFAFA"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

# setting app's icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
